apiVersion: v1
kind: Service
metadata:
  annotations:
    ##https://learn.microsoft.com/en-us/azure/aks/static-ip
    ## <location>.elastic-apm-service
    ##elastic-apm-service.southcentralus.elastic-apm-service
    service.beta.kubernetes.io/azure-dns-label-name: elastic-apm-service
  name: elastic-apm
spec:
  type: LoadBalancer
  ports:
  - port: 8200
  selector:
    app: elastic-agent